### PR TITLE
fixing model definitions, seeing if renaming fixes bug on travis

### PR DESCRIPTION
**Pull request by khayyamsaleem**
i fixed the jwt issue, but now there's another one with env var injection

### CODE REVIEW

**Comment by khayyamsaleem** [comment]
@gluaxspeed fixed the jwt rebinding issue, but now i guess it's not injecting the .env properly; where is it pulled from?

**Comment by khayyamsaleem** [comment]
Do you inject the env vars in from a static store? or is it preconfigured on the build server?

**Comment by khayyamsaleem** [comment]
@robherley wgw dis

**Comment by gluax** [comment]
env is pulled from a local .env file

**Comment by khayyamsaleem** [comment]
@gluaxspeed It's not committed though, so it'll never work on a build server. you need to inject them from some outside source like S3

**Comment by robherley** [comment]
@khayyamsaleem no need to inject (that's kinda trash), we can setup a travis secret: https://docs.travis-ci.com/user/encryption-keys/

**Comment by khayyamsaleem** [comment]
this is the exact same concept, i just didn't know travis had their own

**Comment by robherley** [comment]
see #22

**Pull request closed without merging**
